public struct Crayola {
  public static var red = UIColor(0xED0A3F)
  public static var maroon = UIColor(0xC32148)
  public static var scarlet = UIColor(0xFD0E35)
  public static var brickRed = UIColor(0xC62D42)
  public static var indianRed = UIColor(0xB94E48)
  public static var orangeRed = UIColor(0xFF5349)
  public static var sunsetOrange = UIColor(0xFE4C40)
  public static var bittersweet = UIColor(0xFE6F5E)
  public static var vividTangerine = UIColor(0xFF9980)
  public static var burntOrange = UIColor(0xFF7034)
  public static var redOrange = UIColor(0xFF681F)
  public static var orange = UIColor(0xFF8833)
  public static var macaroniAndCheese = UIColor(0xFFB97B)
  public static var mangoTango = UIColor(0xE77200)
  public static var yellowOrange = UIColor(0xFFAE42)
  public static var bananaMania = UIColor(0xFBE7B2)
  public static var orangeYellow = UIColor(0xF8D568)
  public static var goldenrod = UIColor(0xFCD667)
  public static var dandelion = UIColor(0xFED85D)
  public static var yellow = UIColor(0xFBE870)
  public static var greenYellow = UIColor(0xF1E788)
  public static var oliveGreen = UIColor(0xB5B35C)
  public static var springGreen = UIColor(0xECEBBD)
  public static var canary = UIColor(0xFFFF99)
  
}
