# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: swift 

cache: cocoapods
podfile: Podfile

before_install:
 - rvm get head
 - gem install bundle

script:
 - cd Example
 - bundle update
 - bundle exec fastlane test
