# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift 

before_install:
 - gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
 - rvm get head
install:
 - cd Example
 - gem install bundle 
 - bundle install
 - bundle exec pod install
script:
 - bundle exec fastlane test
