# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.1
language: swift 

before_install:
 - rvm get head
install:
 - cd FlowDKApp
 - gem install bundle 
 - bundle install
 - bundle exec pod install
script:
 - bundle exec fastlane test
